name=input("Enter the name:")
age=int(input("Enter the age:"))
addr=input("Enter the addr:")
num=int(input("Enter the number"))
siblings=int(input("Enter the number of siblings"))
print("name",you have entered)
print("\tage",age)
print("\taddr",addr)
print("\tnum",num)
print("\tsilbings",siblings)
